import type { GameFieldDef } from "../game-fields";

export const PLATFORMS = [
  "PC",
  "Switch 2",
  "Switch",
  "Wii U",
  "Wii",
  "GameCube",
  "N64",
  "PS5",
  "PS4",
  "PS3",
  "PS2",
  "PS1",
  "PSP",
  "Xbox",
] as const;

export const IDENTITY_GAME_FIELDS = [
  {
    id: "id",
    label: "ID",
    type: "string",
    filterable: false,
    sortable: false,
    showInRow: false,
    showInEditor: false,
    defaultValue: "",
  },
  {
    id: "steamAppId",
    label: "Steam App-ID",
    type: "steamAppId",
    filterable: false,
    sortable: false,
    showInRow: false,
    showInEditor: true,
    defaultValue: null,
    group: "identity",
  },
  {
    id: "steamPrice",
    label: "Steam-Preis",
    type: "steamPrice",
    filterable: false,
    sortable: true,
    showInRow: true,
    showInEditor: true,
    rowSlot: "meta",
    defaultValue: null,
    group: "identity",
    readOnly: true,
  },
  {
    id: "igdbId",
    label: "IGDB-ID",
    type: "igdbId",
    filterable: false,
    sortable: false,
    showInRow: false,
    showInEditor: true,
    defaultValue: null,
    group: "identity",
  },
  {
    id: "name",
    label: "Spielname",
    type: "string",
    filterable: false,
    sortable: true,
    showInRow: true,
    showInEditor: true,
    showInHero: true,
    rowSlot: "title",
    defaultValue: "",
    group: "identity",
  },
  {
    id: "coverUrl",
    label: "Cover-URL",
    type: "cover",
    filterable: false,
    sortable: false,
    showInRow: true,
    showInEditor: true,
    showInHero: true,
    rowSlot: "cover",
    defaultValue: "",
    group: "identity",
  },
  {
    id: "franchise",
    label: "Franchise",
    type: "enum",
    allowCustom: true,
    filterMinCount: 2,
    newOptionLabel: "Neue Franchise",
    emptyLabel: "Kein Franchise",
    filterable: true,
    filterWidget: "chips",
    sortable: true,
    showInRow: true,
    showInEditor: true,
    rowSlot: "meta",
    defaultValue: "",
    group: "classification",
  },
  {
    id: "genres",
    label: "Genre",
    type: "multiEnum",
    allowCustom: true,
    newOptionLabel: "Neues Genre",
    maxSelected: 2,
    filterable: true,
    filterWidget: "chips",
    sortable: false,
    showInRow: true,
    showInEditor: true,
    rowSlot: "chips",
    defaultValue: [],
    group: "classification",
  },
  {
    id: "platforms",
    label: "Plattform",
    type: "multiEnum",
    options: PLATFORMS,
    filterable: true,
    filterWidget: "chips",
    sortable: false,
    showInRow: true,
    showInEditor: true,
    rowSlot: "meta",
    defaultValue: [],
    group: "classification",
  },
] as const satisfies readonly GameFieldDef[];
