import type { GameFieldDef } from "../game-fields";

export const LIBRARY_GAME_FIELDS = [
  {
    id: "owned",
    label: "Besitz",
    type: "boolean",
    filterable: true,
    filterWidget: "chips",
    filterGroup: "ownership",
    filterGroupLabel: "Besitz",
    filterTrueLabel: "Im Besitz",
    filterFalseLabel: "Nicht im Besitz",
    sortable: false,
    showInRow: true,
    showInEditor: true,
    rowSlot: "chips",
    defaultValue: false,
    group: "status",
    chipTone: "neutral",
  },
  {
    id: "wishlisted",
    label: "Wunschliste",
    type: "boolean",
    filterable: true,
    filterWidget: "chips",
    filterGroup: "ownership",
    filterGroupLabel: "Besitz",
    filterTrueLabel: "Wunschliste",
    filterFalseLabel: "Nicht auf Wunschliste",
    sortable: false,
    showInRow: true,
    showInEditor: true,
    rowSlot: "chips",
    defaultValue: false,
    group: "status",
    chipTone: "secondary",
  },
  {
    id: "played",
    label: "Gespielt",
    type: "boolean",
    filterable: true,
    filterWidget: "chips",
    filterGroup: "status",
    filterGroupLabel: "Status",
    filterTrueLabel: "Gespielt",
    filterFalseLabel: "Nicht gespielt",
    sortable: false,
    showInRow: true,
    showInEditor: true,
    rowSlot: "chips",
    defaultValue: false,
    group: "status",
    chipTone: "primary",
  },
  {
    id: "finished",
    label: "Durchgespielt",
    type: "boolean",
    filterable: true,
    filterWidget: "chips",
    filterGroup: "status",
    filterGroupLabel: "Status",
    filterTrueLabel: "Durchgespielt",
    filterFalseLabel: "Nicht durchgespielt",
    sortable: false,
    showInRow: true,
    showInEditor: true,
    rowSlot: "chips",
    defaultValue: false,
    group: "status",
    chipTone: "tertiary",
  },
  {
    id: "released",
    label: "Erschienen",
    type: "boolean",
    filterable: true,
    filterWidget: "chips",
    filterTrueLabel: "Erschienen",
    filterFalseLabel: "Noch nicht erschienen",
    sortable: false,
    showInRow: false,
    showInEditor: true,
    defaultValue: true,
    group: "status",
  },
  {
    id: "completed100",
    label: "100%",
    type: "boolean",
    filterable: true,
    filterWidget: "chips",
    filterGroup: "status",
    filterGroupLabel: "Status",
    filterTrueLabel: "100%",
    filterFalseLabel: "Nicht 100%",
    sortable: false,
    showInRow: true,
    showInEditor: true,
    rowSlot: "chips",
    defaultValue: false,
    group: "status",
    chipTone: "tertiary",
  },
  {
    id: "difficultyTo100",
    label: "Schwierigkeit 100%",
    type: "enum",
    allowCustom: true,
    newOptionLabel: "Neue Schwierigkeit",
    emptyLabel: "Keine Angabe",
    filterable: true,
    filterWidget: "chips",
    sortable: true,
    showInRow: true,
    showInEditor: true,
    rowSlot: "meta",
    defaultValue: "",
    group: "progress",
  },
  {
    id: "rating",
    label: "Bewertung",
    type: "rating",
    filterable: true,
    filterWidget: "range",
    sortable: true,
    showInRow: true,
    showInEditor: true,
    rowSlot: "rating",
    defaultValue: null,
    group: "personal",
  },
  {
    id: "priority",
    label: "Spielwarteschlange",
    type: "priority",
    filterable: true,
    filterWidget: "chips",
    sortable: false,
    showInRow: true,
    showInEditor: true,
    rowSlot: "priority",
    defaultValue: null,
    group: "personal",
  },
  {
    id: "queuePosition",
    label: "Spielwarteschlange",
    type: "position",
    filterable: false,
    filterWidget: "chips",
    sortable: true,
    showInRow: false,
    showInEditor: false,
    defaultValue: null,
    group: "personal",
  },
  {
    id: "favoriteRank",
    label: "Persönlicher Rang",
    type: "position",
    filterable: true,
    filterWidget: "chips",
    sortable: true,
    showInRow: false,
    showInEditor: false,
    defaultValue: null,
    group: "personal",
  },
  {
    id: "landscapeArtwork",
    label: "Landscape-Artwork",
    type: "artwork",
    filterable: false,
    sortable: false,
    showInRow: false,
    showInEditor: false,
    defaultValue: null,
    group: "identity",
  },
  {
    id: "caseArtwork",
    label: "Case-Artwork",
    type: "artwork",
    filterable: false,
    sortable: false,
    showInRow: false,
    showInEditor: false,
    defaultValue: null,
    group: "identity",
  },
  {
    id: "provenance",
    label: "Feldherkunft",
    type: "provenance",
    filterable: false,
    sortable: false,
    showInRow: false,
    showInEditor: false,
    defaultValue: {},
    group: "identity",
  },
  {
    id: "notes",
    label: "Notizen",
    type: "text",
    filterable: true,
    filterWidget: "toggle",
    filterTrueLabel: "Hat Notizen",
    sortable: false,
    showInRow: true,
    showInEditor: true,
    rowSlot: "notes",
    defaultValue: "",
    group: "personal",
  },
  {
    id: "playtimeMinutes",
    label: "Spielzeit",
    type: "number",
    filterable: false,
    sortable: true,
    showInRow: true,
    showInEditor: true,
    rowSlot: "meta",
    defaultValue: null,
    group: "progress",
  },
  {
    id: "dateAdded",
    label: "Hinzugefügt",
    type: "date",
    filterable: false,
    sortable: true,
    showInRow: false,
    showInEditor: true,
    defaultValue: null,
    group: "identity",
    readOnly: true,
  },
  {
    id: "lastSynced",
    label: "Zuletzt synchronisiert",
    type: "date",
    filterable: false,
    sortable: false,
    showInRow: false,
    showInEditor: true,
    defaultValue: null,
    group: "progress",
    readOnly: true,
  },
] as const satisfies readonly GameFieldDef[];
