import { normalizeGame, type GameRecord } from "./game-fields";
import { steamCover } from "./steam";

type SeedInput = {
  slug: string;
  name: string;
  steamAppId: number | null;
  franchise: string;
  genres: string[];
  platforms: string[];
  played: boolean;
  finished: boolean;
  released: boolean;
  completed100: boolean;
  difficultyTo100: string;
  owned: boolean;
  wishlisted: boolean;
};

const SEED_ROWS: SeedInput[] = [
  {
    slug: "ffx-x2",
    name: "Final Fantasy X/X-2 HD Remaster",
    steamAppId: 359870,
    franchise: "Final Fantasy",
    genres: ["JRPG"],
    platforms: ["PC"],
    played: true,
    finished: false,
    released: true,
    completed100: false,
    difficultyTo100: "Very High (Grindy + Guide required)",
    owned: true,
    wishlisted: false,
  },
  {
    slug: "ffxv",
    name: "Final Fantasy XV",
    steamAppId: 637650,
    franchise: "Final Fantasy",
    genres: ["Action RPG"],
    platforms: ["PC"],
    played: true,
    finished: false,
    released: true,
    completed100: false,
    difficultyTo100: "High (Grindy)",
    owned: true,
    wishlisted: false,
  },
  {
    slug: "ff7-remake",
    name: "Final Fantasy VII Remake",
    steamAppId: 1462040,
    franchise: "Final Fantasy",
    genres: ["Action RPG"],
    platforms: ["PC"],
    played: true,
    finished: true,
    released: true,
    completed100: false,
    difficultyTo100: "Medium (2 Playthroughs)",
    owned: true,
    wishlisted: false,
  },
  {
    slug: "ff7-rebirth",
    name: "Final Fantasy VII Rebirth",
    steamAppId: 2909400,
    franchise: "Final Fantasy",
    genres: ["Action RPG"],
    platforms: ["PC"],
    played: true,
    finished: true,
    released: true,
    completed100: false,
    difficultyTo100: "Very Hard (2 Playthroughs + Hard Mode)",
    owned: true,
    wishlisted: false,
  },
  {
    slug: "ffxiv",
    name: "Final Fantasy XIV",
    steamAppId: 39210,
    franchise: "Final Fantasy",
    genres: ["MMO", "JRPG"],
    platforms: ["PC"],
    played: true,
    finished: false,
    released: true,
    completed100: false,
    difficultyTo100: "Extremely High (Endless / never true 100%)",
    owned: true,
    wishlisted: false,
  },
  {
    slug: "ffxvi",
    name: "Final Fantasy XVI",
    steamAppId: 2515020,
    franchise: "Final Fantasy",
    genres: ["Action RPG"],
    platforms: ["PC"],
    played: true,
    finished: false,
    released: true,
    completed100: false,
    difficultyTo100: "Medium (2 Playthroughs)",
    owned: false,
    wishlisted: true,
  },
  {
    slug: "ffxiii",
    name: "Final Fantasy XIII",
    steamAppId: 292120,
    franchise: "Final Fantasy",
    genres: ["JRPG"],
    platforms: ["PC"],
    played: false,
    finished: false,
    released: true,
    completed100: false,
    difficultyTo100: "High (Grindy)",
    owned: false,
    wishlisted: true,
  },
  {
    slug: "ffxiii-2",
    name: "Final Fantasy XIII-2",
    steamAppId: 292140,
    franchise: "Final Fantasy",
    genres: ["JRPG"],
    platforms: ["PC"],
    played: false,
    finished: false,
    released: true,
    completed100: false,
    difficultyTo100: "Medium",
    owned: false,
    wishlisted: true,
  },
  {
    slug: "lightning-returns",
    name: "Lightning Returns: Final Fantasy XIII",
    steamAppId: 345350,
    franchise: "Final Fantasy",
    genres: ["Action RPG", "JRPG"],
    platforms: ["PC"],
    played: false,
    finished: false,
    released: true,
    completed100: false,
    difficultyTo100: "Medium (Guide Recommended)",
    owned: false,
    wishlisted: true,
  },
  {
    slug: "kcd",
    name: "Kingdom Come: Deliverance",
    steamAppId: 379430,
    franchise: "Kingdom Come",
    genres: ["Western RPG"],
    platforms: ["PC"],
    played: true,
    finished: true,
    released: true,
    completed100: false,
    difficultyTo100: "High (Grindy + Missables)",
    owned: true,
    wishlisted: false,
  },
  {
    slug: "kcd2",
    name: "Kingdom Come: Deliverance 2",
    steamAppId: 1771300,
    franchise: "Kingdom Come",
    genres: ["Western RPG"],
    platforms: ["PC"],
    played: true,
    finished: true,
    released: true,
    completed100: false,
    difficultyTo100: "High (Grindy)",
    owned: true,
    wishlisted: false,
  },
  {
    slug: "stranger-of-paradise",
    name: "Stranger of Paradise Final Fantasy Origin",
    steamAppId: 1358700,
    franchise: "Final Fantasy",
    genres: ["Action RPG", "Soulslike"],
    platforms: ["PC"],
    played: true,
    finished: false,
    released: true,
    completed100: false,
    difficultyTo100: "Medium (Grindy)",
    owned: true,
    wishlisted: false,
  },
  {
    slug: "crimson-desert",
    name: "Crimson Desert",
    steamAppId: null,
    franchise: "Crimson Desert",
    genres: ["Action RPG"],
    platforms: ["PC"],
    played: true,
    finished: true,
    released: true,
    completed100: false,
    difficultyTo100: "Hard (Grindy)",
    owned: true,
    wishlisted: false,
  },
  {
    slug: "fe-engage",
    name: "Fire Emblem Engage",
    steamAppId: null,
    franchise: "Fire Emblem",
    genres: ["Strategy / Tactics"],
    platforms: ["Switch"],
    played: true,
    finished: true,
    released: true,
    completed100: false,
    difficultyTo100: "High (Grindy)",
    owned: true,
    wishlisted: false,
  },
  {
    slug: "nier-automata",
    name: "NieR:Automata",
    steamAppId: 524220,
    franchise: "Nier",
    genres: ["Action RPG"],
    platforms: ["PC"],
    played: true,
    finished: false,
    released: true,
    completed100: false,
    difficultyTo100: "Medium",
    owned: true,
    wishlisted: false,
  },
  {
    slug: "nier-replicant",
    name: "NieR Replicant",
    steamAppId: 1125520,
    franchise: "Nier",
    genres: ["Action RPG", "JRPG"],
    platforms: ["PC"],
    played: false,
    finished: false,
    released: true,
    completed100: false,
    difficultyTo100: "High (Grindy)",
    owned: false,
    wishlisted: true,
  },
  {
    slug: "ffvi",
    name: "Final Fantasy VI",
    steamAppId: 1173770,
    franchise: "Final Fantasy",
    genres: ["JRPG"],
    platforms: ["PC"],
    played: false,
    finished: false,
    released: true,
    completed100: false,
    difficultyTo100: "High (Grindy)",
    owned: false,
    wishlisted: true,
  },
  {
    slug: "enshrouded",
    name: "Enshrouded",
    steamAppId: 1203620,
    franchise: "Enshrouded",
    genres: ["Survival / Crafting"],
    platforms: ["PC"],
    played: false,
    finished: false,
    released: true,
    completed100: false,
    difficultyTo100: "Low",
    owned: false,
    wishlisted: true,
  },
  {
    slug: "pragmata",
    name: "Pragmata",
    steamAppId: null,
    franchise: "Pragmata",
    genres: ["Action / Adventure"],
    platforms: ["PC"],
    played: false,
    finished: false,
    released: true,
    completed100: false,
    difficultyTo100: "Medium",
    owned: false,
    wishlisted: true,
  },
];

export function createSeedGames(): GameRecord[] {
  return SEED_ROWS.map((row, index) =>
    normalizeGame({
      id: `seed-${row.slug}`,
      name: row.name,
      steamAppId: row.steamAppId,
      coverUrl: row.steamAppId ? steamCover(row.steamAppId, "header") : "",
      franchise: row.franchise,
      genres: row.genres,
      platforms: row.platforms,
      played: row.played,
      finished: row.finished,
      released: row.released,
      completed100: row.completed100,
      difficultyTo100: row.difficultyTo100,
      owned: row.owned,
      wishlisted: row.wishlisted,
      rating: null,
      priority: null,
      notes: "",
      playtimeMinutes: null,
      dateAdded: `2026-01-${String(index + 1).padStart(2, "0")}T12:00:00.000Z`,
      lastSynced: null,
    }),
  );
}

export const SEED_GAMES = createSeedGames();
